#!/bin/bash

# This script supports the following 2 commands :
# 1) Create a basic initramfs based on the following tutorial :
# https://wiki.gentoo.org/wiki/Custom_Initramfs
# 2) List the content of an initramfs archive (compressed using cpio and gzip only)
# 
# For the creation script, the main binary applications installed are the one 
# provided by busybox (ls, mkdir, cp, mount, insmod...)
#
# This script only creates an initramfs archive, to use it the rest of the
# system has to be configured properly meaning :
# 1) Having the kernel configured to enable initramfs (CONFIG_BLK_DEV_INITRD=y)
# 2) Having the kernel configured to use a standalone initramfs archive compressed in gzip format
# (General setup -> Initramfs source file(s) -> Support initial ramdisk/ramfs compressed using gzip)
# 3) Configure grub to recognize the new initramfs file
#
# Requirements (package to be installed) :
# - tree (apt-get install tree)
# - busybox (apt-get install busybox)
#
# cpio and gzip are most of the time part of the base kernel binaries.
#
# Assumptions :
# For the initramfs creation command the init script assumes that the rootfs is located on the
# /dev/sda1 device

# GLOBAL VARIABLES
SUCCESS=1
ERROR=-1

function print_usage () {
	echo "Usage:"
	echo "./initramfs_basictools {create}"
	echo "Creates an initramfs archive (gzip+cpio compressed) that mount the rootfs /dev/sda1"
	echo 
	echo "./initramfs_basictools {list} [file]"
	echo "List the content of an initramfs archive (assume compressed with gzip)"
}

# Create a basic initramfs archive with the device /dev/sda1 as rootfs
function create_initramfs () {
	echo create
}

# Uncompress an initramfs archive in a temporary folder and list its content
# $1 is the file corresponding to the archive
function list_content () {
	if [ ! -r $1 ]; then
		echo "Error: File '$1' does not exist or is not readable"
		exit $ERROR
	fi

	file=`basename $1`
	mkdir tmp && cp $1 tmp/$file && cd tmp
	mv $file $file.gz && gunzip $file.gz
	cpio -i -d -H newc -F $file --no-absolute-filenames 
	rm $file 
	tree .
	cd .. && rm -rf tmp
}

if [ "$#" -lt 1 ]; then
	echo "Error, wrong number of argument"
	print_usage
	exit $ERROR
fi

command="$1"

if [ $command == "create" ]; then
	echo "Creating an initramfs archive..."
	create_initramfs
	exit $SUCCESS
elif [ $command == "list" ]; then
	if [ "$#" != 2 ]; then
		echo "Error: Expect exactly 1 initramfs file"
		print_usage
		exit $ERROR
	fi
	list_content $2
	exit $SUCCESS
fi

# Unknown command
echo "Error: Unknown command '$command'"
print_usage
exit $ERROR
